# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8af03ae626caeea09171cf0c123181bbf73462c1c840ba545867aa0f9146d761952df432f7eb6c50d5113856260ef0079195fe6e5e6c86456c37a59b915123

test:
  secret_key_base: 973db17ed11cd5aed80dccbb8d0ae32093a0678c61b9a6c7a6739a79af5d05c3dc8a3a9194b9f41612050970ffddf0f15462a3f54be9958153329c4fd1dc7463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
